const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    //admin
    ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
    ADMIN_LOGOUT_SUCCESS: 'ADMIN_LOGOUT_SUCCESS',

    // Product
    GET_ALL_PRODUCT_SUCCESS: 'GET_ALL_PRODUCT_SUCCESS',
    CLEAR_LIST_CART: 'CLEAR_LIST_CART',
    RENDER_ALL_BOOKING_SUCCESS: 'RENDER_ALL_BOOKING_SUCCESS',
    GET_HISTORY_ORDER_SUCCESS: 'GET_HISTORY_ORDER_SUCCESS',
    GET_CURRENT_ORDER_SUCCESS: 'GET_CURRENT_ORDER_SUCCESS',
    // ADMIN_LOGIN_FAIL: 'ADMIN_LOGIN_FAIL',
    
    //user
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    GET_USER_CURRENT: "GET_USER_CURRENT",
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',


    
    CREATE_NEW_USER : 'CREATE_NEW_USER',
    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAIL : 'CREATE_USER_FAIL',
    RENDER_ALL_USER: 'RENDER_ALL_USER',
    RENDER_USER_FAIL: 'RENDER_USER_FAIL',
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    EDIT_USER_SUCCESS : 'EDIT_USER_SUCCESS',
    RENDER_DOCTOR : 'RENDER_DOCTORS',
    RENDER_DOCTOR_SUCCESS : 'RENDER_DOCTORS_SUCCESS',

    POST_INFOR_DOCTOR_SUCCESS : 'POST_INFOR_DOCTOR_SUCCESS',
    GET_INFOR_DOCTOR_SUCCESS: 'GET_INFOR_DOCTOR_SUCCESS',

    GET_ALL_CODE_TIME_SUCCESS : 'GET_ALL_CODE_TIME_SUCCESS',
    GET_ALL_CODE_PRICE_PRICE_SUCCESS: 'GET_ALL_CODE_PRICE_PRICE_SUCCESS',
    GET_SCHEDULE_BY_DATE_SUCCESS:'GET_SCHEDULE_BY_DATE_SUCCESS',
    GET_ALL_CODE_PAYMENT_SUCCESS:' GET_ALL_CODE_PAYMENT_SUCCESS',
    GET_ALL_CODE_PROVINCE_SUCCESS: 'GET_ALL_CODE_PROVINCE_SUCCESS',
    GET_USER_BOOKING_SUCCESS : 'GET_USER_BOOKING_SUCCESS',

    // confirm
    CONFIRM_USER_BOOKING_SUCCESS: 'CONFIRM_USER_BOOKING_SUCCESS',

//    The 80
    ADD_PRODUCT_TO_CART_SUCCESS: 'ADD_PRODUCT_TO_CART_SUCCESS:',
    CHANGE_VALUE_PRODUCT_IN_CART : 'CHANGE_VALUE_PRODUCT_IN_CART',
    CHANGE_LIST_PRODUCT: 'CHANGE_LIST_PRODUCT',
    DELETE_ITEM_IN_CART: 'DELETE_ITEM_IN_CART'



})

export default actionTypes;